# docker-compose.yml

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jjp3
      POSTGRES_PASSWORD: BAtFitFMA13#*
      POSTGRES_DB: pka_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./app              # ⬅️ Point to your FastAPI app folder
      dockerfile: Dockerfile
    env_file: .env
    command: sh -c "cd /app && uvicorn main:app --host 0.0.0.0 --port 2911"
    volumes:
      - ./app:/app                # ⬅️ Mount app folder only (not entire root)
    ports:
      - "2911:2911"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: