# /docker-compose.yml
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jjp3
      POSTGRES_PASSWORD: BAtFitFMA13#*
      POSTGRES_DB: pka_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: